server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://139.224.48.178:3306/hmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .html
  ##  static-path-pattern: /static/**
mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: kannan  #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

logging:
  level:
      root: info
      com.mogui.mall.happymall.mapper: debug
